server:
  port: 5555

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetchRegistry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/products-service/**
          filters:
            - StripPrefix=1
  main:
    web-application-type: reactive