spring:
  application:
    name: products-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:marketplace;MODE=PostgreSQL
    username: sa
    password:
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
      open-in-view: false
    h2:
      console:
        enabled: true
        settings:
          web-allow-others: false
server:
  port: 0
#  servlet:
#    context-path: /products-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    hostname: localhost